### ISSUE TITLE
Using this IDW Interpolator for interpolation a function

### ISSUE THREAD

**Issue by siddharthlal25** [JuliaEarth/InverseDistanceWeighting.jl#4]
Thank you for the implementation of this interpolator.

I wanted to use this interpolator for interpolating values of certain points given initial data. 
suppose the value of the function at points is:
```
coordinate   values of the function at the corresponding point
(1,1)            5
(1,5)            6
(2,6)            7
```

Now I want to estimate the value of the function at (2,3).
It would be very nice if you can share a notebook with this kind of example.

Thank you!

**Comment by juliohm** [comment]
Hi @siddharthlal25 , did you have a chance to read the usage notebook? https://github.com/JuliaEarth/InverseDistanceWeighting.jl/blob/master/docs/Usage.ipynb

You may be interested in replacing the `RegularGrid` with a `PointSet` containing the previous points plus the point where you want to estimate. If you can start working on it, I can help you.

**Comment by juliohm** [comment]
Also consider reaching us on our gitter channel for the project.

**Comment by juliohm** [comment]
Closing the issue assuming the notebook helped.

**Comment by siddharthlal25** [comment]
Thank you! The notebook was helpful 😄
